config/routes.rb
MyHrmsRuby::Application.routes.draw do  

  get "/index" => "home#index"
  get "/about" => "home#about"

  match 'overtimes/overview' => 'overtimes#overview', :as => :overview_overtimes
  match 'overtimes/export' => 'overtimes#export', :as => :export_overtimes
  
  resources :permissions

  resources :overtime_states

  resources :groups

  devise_for :users

  resources :overtimes

  root :to => 'home#index'

  
  match 'overtimes/:id/approve' => 'overtimes#approve', :as => :approve_overtime
  match 'overtimes/:id/reject' => 'overtimes#reject', :as => :reject_overtime
  match 'overtimes/:id/apply' => 'overtimes#apply', :as => :apply_overtime
  match 'overtimes/:id/revoke' => 'overtimes#revoke', :as => :revoke_overtime

end

app/models/overtime_state.rb
class OvertimeState < ActiveRecord::Base
end

app/controllers/overtime_states_controller.rb
class OvertimeStatesController < ApplicationController
  # GET /overtime_states
  # GET /overtime_states.json
  def index
    @overtime_states = OvertimeState.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @overtime_states }
    end
  end

  # GET /overtime_states/1
  # GET /overtime_states/1.json
  def show
    @overtime_state = OvertimeState.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @overtime_state }
    end
  end

  # GET /overtime_states/new
  # GET /overtime_states/new.json
  def new
    @overtime_state = OvertimeState.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @overtime_state }
    end
  end

  # GET /overtime_states/1/edit
  def edit
    @overtime_state = OvertimeState.find(params[:id])
  end

  # POST /overtime_states
  # POST /overtime_states.json
  def create
    @overtime_state = OvertimeState.new(params[:overtime_state])

    respond_to do |format|
      if @overtime_state.save
        format.html { redirect_to @overtime_state, notice: 'Overtime state was successfully created.' }
        format.json { render json: @overtime_state, status: :created, location: @overtime_state }
      else
        format.html { render action: "new" }
        format.json { render json: @overtime_state.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /overtime_states/1
  # PUT /overtime_states/1.json
  def update
    @overtime_state = OvertimeState.find(params[:id])

    respond_to do |format|
      if @overtime_state.update_attributes(params[:overtime_state])
        format.html { redirect_to @overtime_state, notice: 'Overtime state was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @overtime_state.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /overtime_states/1
  # DELETE /overtime_states/1.json
  def destroy
    @overtime_state = OvertimeState.find(params[:id])
    @overtime_state.destroy

    respond_to do |format|
      format.html { redirect_to overtime_states_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/overtime_states_helper.rb
module OvertimeStatesHelper
end

app/views/overtime_states/_form.html.erb
<%= form_for(@overtime_state) do |f| %>
  <% if @overtime_state.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@overtime_state.errors.count, "error") %> prohibited this overtime_state from being saved:</h2>

      <ul>
      <% @overtime_state.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :code %><br />
    <%= f.text_field :code %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/overtime_states/edit.html.erb
<h1>Editing overtime_state</h1>

<%= render 'form' %>

<%= link_to 'Show', @overtime_state %> |
<%= link_to 'Back', overtime_states_path %>

app/views/overtime_states/index.html.erb
<h1>Listing overtime_states</h1>

<table>
  <tr>
    <th>Code</th>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @overtime_states.each do |overtime_state| %>
  <tr>
    <td><%= overtime_state.code %></td>
    <td><%= overtime_state.name %></td>
    <td><%= link_to 'Show', overtime_state %></td>
    <td><%= link_to 'Edit', edit_overtime_state_path(overtime_state) %></td>
    <td><%= link_to 'Destroy', overtime_state, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Overtime state', new_overtime_state_path %>

app/views/overtime_states/new.html.erb
<h1>New overtime_state</h1>

<%= render 'form' %>

<%= link_to 'Back', overtime_states_path %>

app/views/overtime_states/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Code:</b>
  <%= @overtime_state.code %>
</p>

<p>
  <b>Name:</b>
  <%= @overtime_state.name %>
</p>


<%= link_to 'Edit', edit_overtime_state_path(@overtime_state) %> |
<%= link_to 'Back', overtime_states_path %>