config/routes.rb
MyHrmsRuby::Application.routes.draw do  

  get "/index" => "home#index"
  get "/about" => "home#about"

  match 'overtimes/overview' => 'overtimes#overview', :as => :overview_overtimes
  match 'overtimes/export' => 'overtimes#export', :as => :export_overtimes
  
  resources :permissions

  resources :overtime_states

  resources :groups

  devise_for :users

  resources :overtimes

  root :to => 'home#index'

  
  match 'overtimes/:id/approve' => 'overtimes#approve', :as => :approve_overtime
  match 'overtimes/:id/reject' => 'overtimes#reject', :as => :reject_overtime
  match 'overtimes/:id/apply' => 'overtimes#apply', :as => :apply_overtime
  match 'overtimes/:id/revoke' => 'overtimes#revoke', :as => :revoke_overtime

end

app/models/permission.rb
class Permission < ActiveRecord::Base
  has_many :group_permissions
  has_many :groups, :through => :group_permissions
  
  def ==(another_permission)
    self.code == another_permission.code
  end
end

app/controllers/permissions_controller.rb
class PermissionsController < ApplicationController
  # GET /permissions
  # GET /permissions.json
  def index
    @permissions = Permission.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @permissions }
    end
  end

  # GET /permissions/1
  # GET /permissions/1.json
  def show
    @permission = Permission.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @permission }
    end
  end

  # GET /permissions/new
  # GET /permissions/new.json
  def new
    @permission = Permission.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @permission }
    end
  end

  # GET /permissions/1/edit
  def edit
    @permission = Permission.find(params[:id])
  end

  # POST /permissions
  # POST /permissions.json
  def create
    @permission = Permission.new(params[:permission])

    respond_to do |format|
      if @permission.save
        format.html { redirect_to @permission, notice: 'Permission was successfully created.' }
        format.json { render json: @permission, status: :created, location: @permission }
      else
        format.html { render action: "new" }
        format.json { render json: @permission.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /permissions/1
  # PUT /permissions/1.json
  def update
    @permission = Permission.find(params[:id])

    respond_to do |format|
      if @permission.update_attributes(params[:permission])
        format.html { redirect_to @permission, notice: 'Permission was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @permission.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /permissions/1
  # DELETE /permissions/1.json
  def destroy
    @permission = Permission.find(params[:id])
    @permission.destroy

    respond_to do |format|
      format.html { redirect_to permissions_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/permissions_helper.rb
module PermissionsHelper
end

app/views/permissions/_form.html.erb
<%= form_for(@permission) do |f| %>
  <% if @permission.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@permission.errors.count, "error") %> prohibited this permission from being saved:</h2>

      <ul>
      <% @permission.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :code %><br />
    <%= f.text_field :code %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/permissions/edit.html.erb
<h1>Editing permission</h1>

<%= render 'form' %>

<%= link_to 'Show', @permission %> |
<%= link_to 'Back', permissions_path %>

app/views/permissions/index.html.erb
<h1>Listing permissions</h1>

<table>
  <tr>
    <th>Code</th>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @permissions.each do |permission| %>
  <tr>
    <td><%= permission.code %></td>
    <td><%= permission.name %></td>
    <td><%= link_to 'Show', permission %></td>
    <td><%= link_to 'Edit', edit_permission_path(permission) %></td>
    <td><%= link_to 'Destroy', permission, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Permission', new_permission_path %>

app/views/permissions/new.html.erb
<h1>New permission</h1>

<%= render 'form' %>

<%= link_to 'Back', permissions_path %>

app/views/permissions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Code:</b>
  <%= @permission.code %>
</p>

<p>
  <b>Name:</b>
  <%= @permission.name %>
</p>


<%= link_to 'Edit', edit_permission_path(@permission) %> |
<%= link_to 'Back', permissions_path %>