config/routes.rb
MyHrmsRuby::Application.routes.draw do  

  get "/index" => "home#index"
  get "/about" => "home#about"

  match 'overtimes/overview' => 'overtimes#overview', :as => :overview_overtimes
  match 'overtimes/export' => 'overtimes#export', :as => :export_overtimes
  
  resources :permissions

  resources :overtime_states

  resources :groups

  devise_for :users

  resources :overtimes

  root :to => 'home#index'

  
  match 'overtimes/:id/approve' => 'overtimes#approve', :as => :approve_overtime
  match 'overtimes/:id/reject' => 'overtimes#reject', :as => :reject_overtime
  match 'overtimes/:id/apply' => 'overtimes#apply', :as => :apply_overtime
  match 'overtimes/:id/revoke' => 'overtimes#revoke', :as => :revoke_overtime

end

app/models/overtime.rb
class Overtime < ActiveRecord::Base
  belongs_to :applicant, :class_name => 'User'
  belongs_to :modified_by, :class_name => 'User', :foreign_key => 'modified_by'
  belongs_to :state, :class_name => 'OvertimeState'
  has_many :user_overtimes
  has_many :participants, :through => :user_overtimes, :source => :user
  has_many :overtime_flows
  has_many :histories, :class_name => 'OvertimeHistory'
      
  validates_presence_of :subject, :on => :create, :message => "can't be blank"
  
  def participants_string
      return self.participants.collect{|x| x.chinese_name}.compact.join(', ')
  end
  
  def total_time
      begin_time = self.start_time
      if self.start_time.hour < 19
          begin_time = Time.new(self.start_time.year, self.start_time.month, self.start_time.day, 19, 0, 0)
      end
      total = ((self.end_time-begin_time)/3600).to_i
      if total < 0
          total = 0
      end
      return total
  end
  
  def self.create_with_flow(user, new_overtime)
    participants = []
    for user_id in new_overtime['participants'].reject!(&:blank?)
      temp_user = User.find(user_id)
      participants.push(temp_user)
    end
    new_overtime['participants'] = participants
    overtime = Overtime.new(new_overtime)
    overtime.state = OvertimeState.find_by_code('ReadyForDirectorApprove')
    overtime.applicant = user
    overtime.modified_by = user
    overtime.save()
      
    # application flow for current user
    current_flow = OvertimeFlow.new
    current_flow.overtime = overtime
    current_flow.applicant = overtime.applicant
    current_flow.set_applicant_state()
    current_flow.save()

    # application flow for participants
    for participant in overtime.participants.all()
      if participant != overtime.applicant
        app_flow = OvertimeFlow.new
        app_flow.overtime = overtime
        app_flow.applicant = participant
        app_flow.set_viewer_state()
        app_flow.save()
      end
    end
    # application flow for superior
    next_flow = OvertimeFlow.new
    next_flow.overtime = overtime
    next_flow.applicant = user.superior
    next_flow.parent = current_flow
    next_flow.set_reviewer_state()
    next_flow.save()
        
    # application history
    overtime.write_history(user)
        
    return overtime
  end
  
  def update_with_flow(user, new_overtime)
    for participant in self.participants
      if participant != self.applicant
        app_flow = self.overtime_flow_by_user(participant)
        if app_flow
          app_flow.delete()
        end
      end
    end
    
    participants = []
    for user_id in new_overtime['participants'].reject!(&:blank?)
      temp_user = User.find(user_id)
      participants.push(temp_user)
    end
    new_overtime['participants'] = participants
    if not self.update_attributes(new_overtime)
      return false
    end
        
    # create application flow for new participants
    for participant in self.participants
      if participant != self.applicant
        app_flow = OvertimeFlow.new
        app_flow.overtime = self
        app_flow.applicant = participant
        app_flow.set_viewer_state()
        app_flow.save() 
      end
    end
    
    return true
  end

  def revoke(user)
      self.state = OvertimeState.find_by_code('Revoke')
      self.save()
        
      flow = self.overtime_flow_by_user(user)
      flow.set_revoke_state()
      flow.save()

      flow = self.overtime_flow_by_user(user.superior)
      flow.delete()
        
      # application history
      self.write_history(user)
        
      return user.superior
  end
        
  def apply(user)
      self.state = OvertimeState.find_by_code('ReadyForDirectorApprove')
      self.save()
        
      current_flow = self.overtime_flow_by_user(user)
      current_flow.set_applicant_state()
      current_flow.save()

      next_flow = OvertimeFlow.new
      next_flow.overtime = self
      next_flow.applicant = user.superior
      next_flow.parent = current_flow
      next_flow.set_reviewer_state()
      next_flow.save()
        
      # application history
      self.write_history(user)
        
      return user.superior
  end

  def reject(user)
      self.state = ApplicationState.objects.get(code='Reject')
      self.save()
        
      flow = self.applicationflow_by_user(user)
      # change parent flow state
      parent_flow = flow.parent
      parent_flow.set_revoke_state()
      parent_flow.save()
      # delete current flow
      flow.delete()
        
      # application history
      self.write_history(user)
        
      return parent_flow.applicant
  end
        
  def approve(user)
      self.state = ApplicationState.objects.get(code='Approved')
      self.save()
        
      applicant_flow = self.applicationflow_by_user(self.applicant)
      applicant_flow.set_hidden_state()
      applicant_flow.save()
        
      current_flow = self.applicationflow_by_user(user)
      if user.userprofile.superior is None
          current_flow.delete()
      else
          current_flow.set_hidden_state()
          current_flow.save()

          next_flow = ApplicationFlow()
          next_flow.application = self
          next_flow.applicant = user.userprofile.superior
          next_flow.parent = current_flow
          next_flow.set_reviewer_state()
          next_flow.save()
      end
      # application history
      self.write_history(user)
  end

  def overtime_flow_by_user(user)
    return self.overtime_flows.where('applicant_id=?', user).first
  end 
  
  def write_history(user)
    history = OvertimeHistory.new
    history.overtime = self
    history.modified_by = user
    history.overtime_state = self.state
    history.save()
    self.modified_by = user
    self.save()
  end

end

app/controllers/overtimes_controller.rb
#!/usr/bin/env ruby
# -*- coding:utf-8 -*-

require 'csv'

class OvertimesController < ApplicationController
  
  before_filter :authenticate_user!
  
  # GET /overtimes
  # GET /overtimes.json
  def index
    @title = '加班'
    
    # not applyed
    revoke_state = OvertimeState.find_by_code('Revoke')
    reject_state = OvertimeState.find_by_code('Reject')
    # approved
    approved_state = OvertimeState.find_by_code('Approved')

    @state_filter = params['state'] || 'all'
    @quick_date_ranges = params['quickDateRanges'] || '7'
    @date_from = params['date_from']
    @date_to = params['date_to']
    @start_time, @end_time, @date_filter = self.get_date_filter(@quick_date_ranges)
    
    if current_user.is_hr?
      # applications = Application.objects.all()
      @overtimes = {
        'all' => Overtime.scoped,
        'new' => Overtime.where(:state => [revoke_state, reject_state]),
        'applying' => Overtime.where(["state_id not in (?)", [revoke_state, reject_state, approved_state]]),
        'approved' => Overtime.where(:state => approved_state),
        }[@state_filter]
      @overtimes = @overtimes.where(:created_at => @start_time..@end_time).order('updated_at DESC')
    else
      @overtime_flows = {
        'all' => current_user.overtime_flows.scoped,
        'new' => current_user.overtime_flows.joins(:overtime).where('overtimes.state_id' => [revoke_state, reject_state]),
        'applying' => current_user.overtime_flows.joins(:overtime).where(["state_id not in (?)", [revoke_state, reject_state, approved_state]]),
        'approved' => current_user.overtime_flows.joins(:overtime).where('overtimes.state_id' => approved_state),
        }[@state_filter]
      @overtime_flows = @overtime_flows.joins(:overtime).where('overtimes.created_at' => @start_time..@end_time).order('updated_at DESC')
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @overtimes }
    end
  end

  # GET /overtimes/1
  # GET /overtimes/1.json
  def show
    @overtime = Overtime.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @overtime }
    end
  end

  # GET /overtimes/new
  # GET /overtimes/new.json
  def new
    @title = '新增加班'
    @overtime = Overtime.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @overtime }
    end
  end

  # GET /overtimes/1/edit
  def edit
    @overtime = Overtime.find(params[:id])
  end

  # POST /overtimes
  # POST /overtimes.json
  def create
    @overtime = Overtime.create_with_flow(current_user, params[:overtime])

    respond_to do |format|
      if @overtime
        subject = '[my_hrms] 新加班申请'
        FlowMailer.flow_notify_email(@overtime, current_user.superior, subject).deliver
        format.html { redirect_to overtimes_path, notice: 'Overtime was successfully created.' }
        format.json { render json: @overtime, status: :created, location: @overtime }
      else
        format.html { render action: "new" }
        format.json { render json: @overtime.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /overtimes/1
  # PUT /overtimes/1.json
  def update
    @overtime = Overtime.find(params[:id])

    respond_to do |format|
      if @overtime.update_with_flow(current_user, params[:overtime])
        format.html { redirect_to @overtime, notice: 'Overtime was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @overtime.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /overtimes/1
  # DELETE /overtimes/1.json
  def destroy
    @overtime = Overtime.find(params[:id])
    @overtime.destroy

    respond_to do |format|
      format.html { redirect_to overtimes_url }
      format.json { head :no_content }
    end
  end
  
  def revoke
    @overtime = Overtime.find(params[:id])
    @overtime.revoke(current_user)
    subject = '[my_hrms] 加班撤销'
    FlowMailer.flow_notify_email(@overtime, current_user.superior, subject).deliver
    redirect_to overtimes_path
  end
  
  def apply
    @overtime = Overtime.find(params[:id])
    @overtime.apply(current_user)
    subject = '[my_hrms] 新加班申请'
    FlowMailer.flow_notify_email(@overtime, current_user.superior, subject).deliver
    redirect_to overtimes_path
  end
  
  def overview
    @title = '加班统计'
    
    @quick_date_ranges = params['quickDateRanges'] || '7'
    @date_from = params['date_from']
    @date_to = params['date_to']
    @start_time, @end_time, @date_filter = self.get_date_filter(@quick_date_ranges)
    
    approved_state = OvertimeState.find_by_code('Approved')
    @overtime_flows = current_user.overtime_flows.joins(:overtime).where('overtimes.state_id' => approved_state)
    @overtime_flows = @overtime_flows.joins(:overtime).where('overtimes.created_at' => @start_time..@end_time).order('updated_at DESC')
  end
  
  def export
    @quick_date_ranges = params['quickDateRanges'] || '7'
    @date_from = params['date_from']
    @date_to = params['date_to']
    @start_time, @end_time, @date_filter = self.get_date_filter(@quick_date_ranges)
    
    approved_state = OvertimeState.find_by_code('Approved')
    @overtime_flows = current_user.overtime_flows.joins(:overtime).where('overtimes.state_id' => approved_state)
    @overtime_flows = @overtime_flows.joins(:overtime).where('overtimes.created_at' => @start_time..@end_time).order('updated_at DESC')
    
    respond_to do |format|
      format.csv {
        send_data(csv_content_for(@overtime_flows),  
        :type => "text/csv;charset=utf-8; header=present",  
        :filename => "Report_Overtimes_#{Time.now.strftime("%Y%m%d")}.csv") 
      }
    end
  end
  
  def csv_content_for(overtime_flows)
    csv_string = CSV.generate do |csv|
      csv << ["基本信息"]
      csv << ["姓名", current_user.chinese_name]
      csv << ["部门"]
      csv << ["入职日期"]
      csv << ["已休年假天数"]
      csv << ["年假剩余天数"]
      csv << ['']
      csv << ["加班信息"]
      csv << ['', "标题", "开始时间", "结束时间", "加班时间(小时)"]
      
      overtime_flows.each_with_index do |flow, index|
        csv << [index+1, flow.overtime.subject, flow.overtime.start_time, flow.overtime.end_time, flow.overtime.total_time]
      end
    end
    return csv_string
  end
  
  def get_date_filter(quick_date_ranges)
      start_time = ''
      end_time = ''
      date_filter = ''
      # date_filter = '1'
      case quick_date_ranges        
      when '0'  # custom
        start_time = DateTime.strptime(params['date_from'], '%Y-%m-%d')
        end_time = DateTime.strptime(params['date_to'], '%Y-%m-%d')
        end_time = Time.new(end_time.year, end_time.month, end_time.day, 23, 59, 59)
        date_filter = '时间范围：' + params['date_from'] + ' - ' + params['date_to']
      when '1'  # today
        now = Time.now
        start_time = Time.new(now.year, now.month, now.day, 0, 0, 0)
        end_time = Time.new(now.year, now.month, now.day, 23, 59, 59)
        date_filter = '时间范围：' + now.strftime('%Y-%m-%d')
      when '2'  # yestoday
        now = Time.now
        yestoday = now - 1.day
        start_time = Time.new(yestoday.year, yestoday.month, yestoday.day, 0, 0, 0)
        end_time = Time.new(yestoday.year, yestoday.month, yestoday.day, 23, 59, 59)
        date_filter = '时间范围：' + yestoday.strftime('%Y-%m-%d')
      when '3' # this week
        now = Time.now
        monday = now - (now.wday-1).day
        sunday = monday + 6.day
        start_time = Time.new(monday.year, monday.month, monday.day, 0, 0, 0)
        end_time = Time.new(sunday.year, sunday.month, sunday.day, 23, 59, 59)
        date_filter = '时间范围：' + start_time.strftime('%Y-%m-%d') + ' - ' + end_time.strftime('%Y-%m-%d')
      when '4'  # last week
        now = Time.now
        last_monday = now - (now.wday-1+7).day
        last_sunday = last_monday + 6.day
        start_time = Time.new(last_monday.year, last_monday.month, last_monday.day, 0, 0, 0)
        end_time = Time.new(last_sunday.year, last_sunday.month, last_sunday.day, 23, 59, 59)
        date_filter = '时间范围：' + start_time.strftime('%Y-%m-%d') + ' - ' + end_time.strftime('%Y-%m-%d')
      when '5'  # this month
        now = Time.now
        first_day_of_month = Time.new(now.year, now.month, 1, 0, 0, 0)
        last_day_of_month = Time.new(now.year, now.month+1, 1, 0, 0, 0) - 1.day
        start_time = Time.new(first_day_of_month.year, first_day_of_month.month, first_day_of_month.day, 0, 0, 0)
        end_time = Time.new(last_day_of_month.year, last_day_of_month.month, last_day_of_month.day, 23, 59, 59)
        date_filter = first_day_of_month.strftime('时间范围：%Y年%m月')
      when '6'  # last month
        now = Time.now
        first_day_of_month = Time.new(now.year, now.month-1)
        last_day_of_month = Time.new(now.year, now.month, 1, 0, 0, 0) - 1.day
        start_time = Time.new(first_day_of_month.year, first_day_of_month.month, first_day_of_month.day, 0, 0, 0)
        end_time = Time.new(last_day_of_month.year, last_day_of_month.month, last_day_of_month.day, 23, 59, 59)
        date_filter = first_day_of_month.strftime('时间范围：%Y年%m月')
      when '7'  # this year
        now = Time.now
        start_time = Time.new(now.year, 1, 1, 0, 0, 0)
        end_time = Time.new(now.year, 12, 31, 23, 59, 59)
        # date_filter = u'时间范围：' + u'%s年' % (now.year)
        date_filter = now.strftime('时间范围：%Y年')
      when '8'  # last year
        now = Time.now
        start_time = Time.new(now.year-1, 1, 1, 0, 0, 0)
        end_time = Time.new(now.year-1, 12, 31, 23, 59, 59)
        date_filter = '时间范围：%d年' % (now.year-1)
      end
        
      return [start_time, end_time, date_filter]
  end
end

app/helpers/overtimes_helper.rb
module OvertimesHelper
end

app/views/overtimes/_form.html.erb
<%= form_for(@overtime, :html => { :class => 'form-horizontal' }) do |f| %>
  <% if @overtime.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@overtime.errors.count, "error") %> prohibited this overtime from being saved:</h2>

      <ul>
      <% @overtime.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label :subject, '标题', :class=>'control-label' %>
    <div class="controls">
      <%= f.text_field :subject %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :start_time, '开始时间', :class=>'control-label' %>
    <div class="controls">
      <%= f.text_field :start_time %>
    </div>
  </div>  
  <div class="control-group">
    <%= f.label :end_time, '结束时间', :class=>'control-label' %>
    <div class="controls">
      <%= f.text_field :end_time %>
    </div>
  </div>
  <div class="control-group">
  <%= f.label :participants, '参加人员', :class=>'control-label' %>
    <div class="controls">
      <%= f.select :participants, options_from_collection_for_select(User.all, :id, :chinese_name), {}, {:multiple => true} %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :content, '备注', :class=>'control-label' %>
    <div class="controls">
      <%= f.text_area :content, :rows => 10 %>
    </div>
  </div>
  <div class="control-group">
    <div class="controls">
      <%= f.submit '提交', :class=>'btn' %>
    </div>
  </div>
<% end %>

<p>
  <%= link_to '返回', overtimes_path, :class=>'btn' %>
</p>

<% content_for :js do %>

<script type="text/javascript" charset="utf-8">
  $('#overtime_start_time').datetimepicker({dateFormat: "yy-mm-dd"});
  $('#overtime_end_time').datetimepicker({dateFormat: "yy-mm-dd"});
</script>

<% end %>

app/views/overtimes/edit.html.erb
<ul class="breadcrumb">
  <li><a href="/">首页</a> <span class="divider">/</span></li>
  <li><%= link_to '加班系统', overtimes_path %> <span class="divider">/</span></li>
  <li class="active">修改加班</li>
</ul>

<h1>修改加班</h1>

<%= render 'form' %>

app/views/overtimes/index.html.erb
<ul class="breadcrumb">
  <li><a href="/">首页</a> <span class="divider">/</span></li>
  <li class="active">加班系统</li>
</ul>

<div class="page-header"><h1>加班列表</h1></div>
  
<p>
  <% if current_user.can_add_overtime? %><%= link_to '新增加班申请', new_overtime_path, :class=>'btn' %><% end %>
  <%= link_to '加班统计', overview_overtimes_path(:state => 'all', :quickDateRanges => @quick_date_ranges, :date_from => @date_from, :date_to => @date_to), :class => 'btn' %>
</p>
      
<% if current_user.can_filter_overtime? %>
<p>
  <span id="date-filter" class="pull-right" onclick="showDatePicker();"><%= @date_filter %></span>
  <ul class="nav nav-tabs">
    <li class="<% if @state_filter == 'all' %>active<% end %>"><%= link_to '全部', overtimes_path(:state => 'all', :quickDateRanges => @quick_date_ranges, :date_from => @date_from, :date_to => @date_to) %></a></li>
    <li class="<% if @state_filter == 'new' %>active<% end %>"><%= link_to '未提交', overtimes_path(:state => 'new', :quickDateRanges => @quick_date_ranges, :date_from => @date_from, :date_to => @date_to) %></li>
    <li class="<% if @state_filter == 'applying' %>active<% end %>"><%= link_to '申请中', overtimes_path(:state => 'applying', :quickDateRanges => @quick_date_ranges, :date_from => @date_from, :date_to => @date_to) %></li>
    <li class="<% if @state_filter == 'approved' %>active<% end %>"><%= link_to '通过', overtimes_path(:state => 'approved', :quickDateRanges => @quick_date_ranges, :date_from => @date_from, :date_to => @date_to) %></li>
  </ul>
</p>
<% end %>

<% if current_user.is_hr? %>
  <% @overtimes.each do |overtime| %>
  <li>
      <h3><a href="{% url show_overtime app.id %}"><%= overtime.subject %></a></h3>
      <%= overtime.state.name %>
      <div class="foot">最后由 • <span class="field"><%= overtime.modified_by.chinese_name %></span> • 于 • <span class="field"><%= overtime.updated_at %></span> • 修改</div>
  </li>
  <% end %>
<% else %>
  <% for flow in @overtime_flows %>
<div class="row">
  <div class="span12">
    <h4>
      <%= link_to flow.overtime.subject, overtime_path(flow.overtime) %>
      <span class="label label-<%= flow.overtime.state.code %>" id="app_state"><%= flow.overtime.state.name %></span>
    </h4>
    <small>最后由 • <strong><%= flow.overtime.modified_by.chinese_name %></strong> • 于 • <strong><%= flow.updated_at %></strong> • 修改</small>
    <div class="pull-right">
      <% if flow.can_update %><%= link_to '修改', edit_overtime_path(flow.overtime), :class => 'btn btn-small' %><% end %>
      <% if flow.can_approve %><%= link_to '通过', approve_overtime_path(flow.overtime), :class => 'btn btn-small' %><% end %>
      <% if flow.can_reject %><%= link_to '拒绝', reject_overtime_path(flow.overtime), :class => 'btn btn-small' %><% end %>
      <% if flow.can_apply %><%= link_to '提交', apply_overtime_path(flow.overtime), :class => 'btn btn-small' %><% end %>
      <% if flow.can_revoke %><%= link_to '撤销', revoke_overtime_path(flow.overtime), :class => 'btn btn-small' %><% end %>
      <% if flow.can_delete %><%= link_to '删除', flow.overtime, :method => :delete, :class => 'btn btn-small', :confirm => '删除以后不能恢复的，确定？' %><% end %>
    </div>
  </div>
</div>
<hr>
  <% end %>
<% end %>

app/views/overtimes/new.html.erb
<ul class="breadcrumb">
  <li><a href="/">首页</a> <span class="divider">/</span></li>
  <li><%= link_to '加班系统', overtimes_path %> <span class="divider">/</span></li>
  <li class="active">新增加班</li>
</ul>

<h1>新增加班</h1>

<%= render 'form' %>

app/views/overtimes/overview.html.erb
  <ul class="breadcrumb">
    <li><a href="/">首页</a> <span class="divider">/</span></li>
    <li><a href="/overtimes">加班系统</a> <span class="divider">/</span></li>
    <li class="active">加班统计</li>
  </ul>

  <div class="page-header"><h1>加班统计</h1></div>
  
  <span class="pull-right" id="date-filter" onclick="showDatePicker();"><%= @date_filter %></span>
  <%= link_to '导出报表', export_overtimes_path(:format => 'csv'), :class => 'btn' %>

  <div class="row">
    <div class="span5">
      <h2>基本信息</h2>
      <table class="table table-condensed">
        <tbody>
          <tr><th>姓名</th><td><%= current_user.chinese_name %></td></tr>
          <tr><th>部门</th><td></td></tr>
          <tr><th>入职日期</th><td></td></tr>
          <tr><th>已休年假天数</th><td></td></tr>
          <tr><th>年假剩余天数</th><td></td></tr>
        </tbody>
      </table>
    </div>
  </div>

  <div class="row">
    <div class="span12">
      <h2>加班信息</h2>
      <table class="table table-striped table-condensed">
        <thead><tr><th>#</th><th>标题</th><th>开始时间</th><th>结束时间</th><th>加班时间(小时)</th></tr></thead>
        <tbody>
          <% @overtime_flows.each_with_index do |flow, index| %>
          <tr><td><%= index+1 %></td><td><%= flow.overtime.subject %></td><td><%= flow.overtime.start_time %></td><td><%= flow.overtime.end_time %></td><td><%= flow.overtime.total_time %></td></tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>

  <p>
    <%= link_to '返回', overtimes_path, :class=>'btn' %>
  </p>

app/views/overtimes/show.html.erb
<p id="notice"><%= notice %></p>

<ul class="breadcrumb">
  <li><a href="/">首页</a> <span class="divider">/</span></li>
  <li><li><%= link_to '加班系统', overtimes_path %> <span class="divider">/</span></li>
  <li class="active">加班详情</li>
</ul>

<div class="page-header"><h1><%= @overtime.subject %></h1></div>

<div class="row">
  <div class="span5">
    <table class="table table-condensed">
      <tr><th>主题:</th><td><%= @overtime.subject %></td></tr>
      <tr><th>申请人:</th><td><%= @overtime.applicant.chinese_name %></td></tr>
      <tr><th>开始时间:</th><td><%= @overtime.start_time %></td></tr>
      <tr><th>结束时间:</th><td><%= @overtime.end_time %></td></tr>
      <tr><th>申请日期:</th><td><%= @overtime.created_at %></td></tr>
      <tr><th>参加人员:</th><td><%= @overtime.participants_string %></td></tr>
      <tr><th>备注:</th><td><%= @overtime.content %></td></tr>
      <tr><th>状态:</th><td><%= @overtime.state.name %></td></tr>
    </table>
  </div>
</div>

<h2>修改历史</h2>
<table class="table table-condensed">
  <thead><tr><th>时间</th><th>修改人</th><th>状态</th></tr></thead>
  <tbody>
  <% for history in @overtime.histories %>
  <tr><td><%= history.created_at %></td><td><%= history.modified_by.chinese_name %></td><td><%= history.overtime_state.name %></td></tr>
  <% end %>
  </tbody>
</table>

<p>
  <%= link_to '返回', overtimes_path, :class=>'btn' %>
</p>